/**
 * FDS
 * This API allows to communicate with FDS (Food Delivery System) server. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package deliveryApp.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.List;

import io.swagger.annotations.*;

@ApiModel(description = "")
public class FoodItem {
  
  @SerializedName("itemId")
  private String itemId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("thumbnail")
  private String thumbnail = null;
  @SerializedName("vendor")
  private String vendor = null;
  @SerializedName("price")
  private BigDecimal price = null;
  @SerializedName("rating")
  private BigDecimal rating = null;
  @SerializedName("ratedBy")
  private BigDecimal ratedBy = null;
  @SerializedName("tags")
  private List<String> tags = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getItemId() {
    return itemId;
  }
  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getThumbnail() {
    return thumbnail;
  }
  public void setThumbnail(String thumbnail) {
    this.thumbnail = thumbnail;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getVendor() {
    return vendor;
  }
  public void setVendor(String vendor) {
    this.vendor = vendor;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getPrice() {
    return price;
  }
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getRating() {
    return rating;
  }
  public void setRating(BigDecimal rating) {
    this.rating = rating;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getRatedBy() {
    return ratedBy;
  }
  public void setRatedBy(BigDecimal ratedBy) {
    this.ratedBy = ratedBy;
  }

  /**
   * tags related to food item
   **/
  @ApiModelProperty(value = "tags related to food item")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FoodItem foodItem = (FoodItem) o;
    return (this.itemId == null ? foodItem.itemId == null : this.itemId.equals(foodItem.itemId)) &&
        (this.name == null ? foodItem.name == null : this.name.equals(foodItem.name)) &&
        (this.thumbnail == null ? foodItem.thumbnail == null : this.thumbnail.equals(foodItem.thumbnail)) &&
        (this.vendor == null ? foodItem.vendor == null : this.vendor.equals(foodItem.vendor)) &&
        (this.price == null ? foodItem.price == null : this.price.equals(foodItem.price)) &&
        (this.rating == null ? foodItem.rating == null : this.rating.equals(foodItem.rating)) &&
        (this.ratedBy == null ? foodItem.ratedBy == null : this.ratedBy.equals(foodItem.ratedBy)) &&
        (this.tags == null ? foodItem.tags == null : this.tags.equals(foodItem.tags));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.itemId == null ? 0: this.itemId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.thumbnail == null ? 0: this.thumbnail.hashCode());
    result = 31 * result + (this.vendor == null ? 0: this.vendor.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.rating == null ? 0: this.rating.hashCode());
    result = 31 * result + (this.ratedBy == null ? 0: this.ratedBy.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FoodItem {\n");
    
    sb.append("  itemId: ").append(itemId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  thumbnail: ").append(thumbnail).append("\n");
    sb.append("  vendor: ").append(vendor).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  rating: ").append(rating).append("\n");
    sb.append("  ratedBy: ").append(ratedBy).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
