/**
 * FDS
 * This API allows to communicate with FDS (Food Delivery System) server. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package deliveryApp.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import io.swagger.annotations.*;

@ApiModel(description = "")
public class Order {
  
  @SerializedName("orderId")
  private String orderId = null;
  @SerializedName("customerName")
  private String customerName = null;
  @SerializedName("deliveryAddress")
  private String deliveryAddress = null;
  @SerializedName("pickupLocation")
  private String pickupLocation = null;
  @SerializedName("orderDetails")
  private List<OrderItem> orderDetails = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrderId() {
    return orderId;
  }
  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCustomerName() {
    return customerName;
  }
  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDeliveryAddress() {
    return deliveryAddress;
  }
  public void setDeliveryAddress(String deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPickupLocation() {
    return pickupLocation;
  }
  public void setPickupLocation(String pickupLocation) {
    this.pickupLocation = pickupLocation;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<OrderItem> getOrderDetails() {
    return orderDetails;
  }
  public void setOrderDetails(List<OrderItem> orderDetails) {
    this.orderDetails = orderDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return (this.orderId == null ? order.orderId == null : this.orderId.equals(order.orderId)) &&
        (this.customerName == null ? order.customerName == null : this.customerName.equals(order.customerName)) &&
        (this.deliveryAddress == null ? order.deliveryAddress == null : this.deliveryAddress.equals(order.deliveryAddress)) &&
        (this.pickupLocation == null ? order.pickupLocation == null : this.pickupLocation.equals(order.pickupLocation)) &&
        (this.orderDetails == null ? order.orderDetails == null : this.orderDetails.equals(order.orderDetails));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.orderId == null ? 0: this.orderId.hashCode());
    result = 31 * result + (this.customerName == null ? 0: this.customerName.hashCode());
    result = 31 * result + (this.deliveryAddress == null ? 0: this.deliveryAddress.hashCode());
    result = 31 * result + (this.pickupLocation == null ? 0: this.pickupLocation.hashCode());
    result = 31 * result + (this.orderDetails == null ? 0: this.orderDetails.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    
    sb.append("  orderId: ").append(orderId).append("\n");
    sb.append("  customerName: ").append(customerName).append("\n");
    sb.append("  deliveryAddress: ").append(deliveryAddress).append("\n");
    sb.append("  pickupLocation: ").append(pickupLocation).append("\n");
    sb.append("  orderDetails: ").append(orderDetails).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
