/**
 * FDS
 * This API allows to communicate with FDS (Food Delivery System) server. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package deliveryApp.model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.*;

@ApiModel(description = "")
public class Profile {
  
  @SerializedName("username")
  private String username = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("phone")
  private String phone = null;
  @SerializedName("email")
  private String email = null;
  public enum GenderEnum {
     Male,  Female,  Others, 
  };
  @SerializedName("gender")
  private GenderEnum gender = null;
  @SerializedName("dob")
  private String dob = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public GenderEnum getGender() {
    return gender;
  }
  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDob() {
    return dob;
  }
  public void setDob(String dob) {
    this.dob = dob;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Profile profile = (Profile) o;
    return (this.username == null ? profile.username == null : this.username.equals(profile.username)) &&
        (this.name == null ? profile.name == null : this.name.equals(profile.name)) &&
        (this.phone == null ? profile.phone == null : this.phone.equals(profile.phone)) &&
        (this.email == null ? profile.email == null : this.email.equals(profile.email)) &&
        (this.gender == null ? profile.gender == null : this.gender.equals(profile.gender)) &&
        (this.dob == null ? profile.dob == null : this.dob.equals(profile.dob));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.phone == null ? 0: this.phone.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.gender == null ? 0: this.gender.hashCode());
    result = 31 * result + (this.dob == null ? 0: this.dob.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Profile {\n");
    
    sb.append("  username: ").append(username).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  gender: ").append(gender).append("\n");
    sb.append("  dob: ").append(dob).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
