# coding: utf-8

"""
    FDS

    This API allows to communicate with FDS (Food Delivery System) server. 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from FoodDeliveryAPI.models.user_details import UserDetails

class TestUserDetails(unittest.TestCase):
    """UserDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDetails:
        """Test UserDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDetails`
        """
        model = UserDetails()
        if include_optional:
            return UserDetails(
                username = 'testUser1',
                password = '1234@Abcd',
                name = 'Test D. User',
                phone = '9876543210',
                email = 'email@example.com',
                gender = 'Male',
                dob = '01-01-2000'
            )
        else:
            return UserDetails(
                username = 'testUser1',
                password = '1234@Abcd',
                phone = '9876543210',
        )
        """

    def testUserDetails(self):
        """Test UserDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
