# coding: utf-8

"""
    FDS

    This API allows to communicate with FDS (Food Delivery System) server. 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from FoodDeliveryAPI.models.food_item_full import FoodItemFull

class TestFoodItemFull(unittest.TestCase):
    """FoodItemFull unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoodItemFull:
        """Test FoodItemFull
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FoodItemFull`
        """
        model = FoodItemFull()
        if include_optional:
            return FoodItemFull(
                item_id = '',
                item_name = '',
                thumbnail_picture = '',
                price = 1.337,
                vendor_name = '',
                vendor_location = '',
                star_rating = 1.337,
                is_available = True,
                max_quantity = 56,
                image_urls = [
                    ''
                    ],
                tags = [
                    ''
                    ]
            )
        else:
            return FoodItemFull(
        )
        """

    def testFoodItemFull(self):
        """Test FoodItemFull"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
