# coding: utf-8

"""
    FDS

    This API allows to communicate with FDS (Food Delivery System) server. 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from FoodDeliveryAPI.models.vendor_get_requested_orders200_response_inner import VendorGetRequestedOrders200ResponseInner

class TestVendorGetRequestedOrders200ResponseInner(unittest.TestCase):
    """VendorGetRequestedOrders200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VendorGetRequestedOrders200ResponseInner:
        """Test VendorGetRequestedOrders200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VendorGetRequestedOrders200ResponseInner`
        """
        model = VendorGetRequestedOrders200ResponseInner()
        if include_optional:
            return VendorGetRequestedOrders200ResponseInner(
                order_id = '',
                user_id = '',
                vendor_id = '',
                pickup_location = '',
                order_items = [
                    FoodDeliveryAPI.models.vendor_get_requested_orders_200_response_inner_order_items_inner.vendorGetRequestedOrders_200_response_inner_orderItems_inner(
                        item_id = '0123456789101112131415161718192021222324252627282930313233343536373839', 
                        quantity = 1.337, )
                    ],
                location = '',
                price = 1.337
            )
        else:
            return VendorGetRequestedOrders200ResponseInner(
        )
        """

    def testVendorGetRequestedOrders200ResponseInner(self):
        """Test VendorGetRequestedOrders200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
