# coding: utf-8

"""
    FDS

    This API allows to communicate with FDS (Food Delivery System) server. 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from FoodDeliveryAPI.models.vendor_details import VendorDetails

class TestVendorDetails(unittest.TestCase):
    """VendorDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VendorDetails:
        """Test VendorDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VendorDetails`
        """
        model = VendorDetails()
        if include_optional:
            return VendorDetails(
                username = 'testVendor1',
                password = '1234@Ved',
                name = 'UltraTech Cafe',
                phone = '9878543210',
                email = 'vendor001@example.com',
                location = 'Mess Block'
            )
        else:
            return VendorDetails(
                username = 'testVendor1',
                password = '1234@Ved',
                phone = '9878543210',
                location = 'Mess Block',
        )
        """

    def testVendorDetails(self):
        """Test VendorDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
