from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DeliveryAcceptOrderPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, order_id=None):  # noqa: E501
        """DeliveryAcceptOrderPostRequest - a model defined in OpenAPI

        :param order_id: The order_id of this DeliveryAcceptOrderPostRequest.  # noqa: E501
        :type order_id: str
        """
        self.openapi_types = {
            'order_id': str
        }

        self.attribute_map = {
            'order_id': 'orderId'
        }

        self._order_id = order_id

    @classmethod
    def from_dict(cls, dikt) -> 'DeliveryAcceptOrderPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _delivery_acceptOrder_post_request of this DeliveryAcceptOrderPostRequest.  # noqa: E501
        :rtype: DeliveryAcceptOrderPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> str:
        """Gets the order_id of this DeliveryAcceptOrderPostRequest.


        :return: The order_id of this DeliveryAcceptOrderPostRequest.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: str):
        """Sets the order_id of this DeliveryAcceptOrderPostRequest.


        :param order_id: The order_id of this DeliveryAcceptOrderPostRequest.
        :type order_id: str
        """
        if order_id is not None and len(order_id) > 40:
            raise ValueError("Invalid value for `order_id`, length must be less than or equal to `40`")  # noqa: E501
        if order_id is not None and len(order_id) < 40:
            raise ValueError("Invalid value for `order_id`, length must be greater than or equal to `40`")  # noqa: E501

        self._order_id = order_id
