from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DeliveryDropOrderPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, order_id=None, otp=None):  # noqa: E501
        """DeliveryDropOrderPostRequest - a model defined in OpenAPI

        :param order_id: The order_id of this DeliveryDropOrderPostRequest.  # noqa: E501
        :type order_id: str
        :param otp: The otp of this DeliveryDropOrderPostRequest.  # noqa: E501
        :type otp: int
        """
        self.openapi_types = {
            'order_id': str,
            'otp': int
        }

        self.attribute_map = {
            'order_id': 'orderId',
            'otp': 'otp'
        }

        self._order_id = order_id
        self._otp = otp

    @classmethod
    def from_dict(cls, dikt) -> 'DeliveryDropOrderPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _delivery_dropOrder_post_request of this DeliveryDropOrderPostRequest.  # noqa: E501
        :rtype: DeliveryDropOrderPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> str:
        """Gets the order_id of this DeliveryDropOrderPostRequest.


        :return: The order_id of this DeliveryDropOrderPostRequest.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: str):
        """Sets the order_id of this DeliveryDropOrderPostRequest.


        :param order_id: The order_id of this DeliveryDropOrderPostRequest.
        :type order_id: str
        """

        self._order_id = order_id

    @property
    def otp(self) -> int:
        """Gets the otp of this DeliveryDropOrderPostRequest.


        :return: The otp of this DeliveryDropOrderPostRequest.
        :rtype: int
        """
        return self._otp

    @otp.setter
    def otp(self, otp: int):
        """Sets the otp of this DeliveryDropOrderPostRequest.


        :param otp: The otp of this DeliveryDropOrderPostRequest.
        :type otp: int
        """

        self._otp = otp
