from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class OrderItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, item_id=None, item_name=None, quantity=None, price=None):  # noqa: E501
        """OrderItem - a model defined in OpenAPI

        :param item_id: The item_id of this OrderItem.  # noqa: E501
        :type item_id: str
        :param item_name: The item_name of this OrderItem.  # noqa: E501
        :type item_name: str
        :param quantity: The quantity of this OrderItem.  # noqa: E501
        :type quantity: int
        :param price: The price of this OrderItem.  # noqa: E501
        :type price: float
        """
        self.openapi_types = {
            'item_id': str,
            'item_name': str,
            'quantity': int,
            'price': float
        }

        self.attribute_map = {
            'item_id': 'itemId',
            'item_name': 'itemName',
            'quantity': 'quantity',
            'price': 'price'
        }

        self._item_id = item_id
        self._item_name = item_name
        self._quantity = quantity
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'OrderItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The orderItem of this OrderItem.  # noqa: E501
        :rtype: OrderItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item_id(self) -> str:
        """Gets the item_id of this OrderItem.


        :return: The item_id of this OrderItem.
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id: str):
        """Sets the item_id of this OrderItem.


        :param item_id: The item_id of this OrderItem.
        :type item_id: str
        """

        self._item_id = item_id

    @property
    def item_name(self) -> str:
        """Gets the item_name of this OrderItem.


        :return: The item_name of this OrderItem.
        :rtype: str
        """
        return self._item_name

    @item_name.setter
    def item_name(self, item_name: str):
        """Sets the item_name of this OrderItem.


        :param item_name: The item_name of this OrderItem.
        :type item_name: str
        """

        self._item_name = item_name

    @property
    def quantity(self) -> int:
        """Gets the quantity of this OrderItem.


        :return: The quantity of this OrderItem.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this OrderItem.


        :param quantity: The quantity of this OrderItem.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def price(self) -> float:
        """Gets the price of this OrderItem.


        :return: The price of this OrderItem.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this OrderItem.


        :param price: The price of this OrderItem.
        :type price: float
        """

        self._price = price
