from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PlaceOrderRequestItemCartInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, item_id=None, quantity=None):  # noqa: E501
        """PlaceOrderRequestItemCartInner - a model defined in OpenAPI

        :param item_id: The item_id of this PlaceOrderRequestItemCartInner.  # noqa: E501
        :type item_id: str
        :param quantity: The quantity of this PlaceOrderRequestItemCartInner.  # noqa: E501
        :type quantity: float
        """
        self.openapi_types = {
            'item_id': str,
            'quantity': float
        }

        self.attribute_map = {
            'item_id': 'itemId',
            'quantity': 'quantity'
        }

        self._item_id = item_id
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'PlaceOrderRequestItemCartInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The placeOrder_request_itemCart_inner of this PlaceOrderRequestItemCartInner.  # noqa: E501
        :rtype: PlaceOrderRequestItemCartInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item_id(self) -> str:
        """Gets the item_id of this PlaceOrderRequestItemCartInner.


        :return: The item_id of this PlaceOrderRequestItemCartInner.
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id: str):
        """Sets the item_id of this PlaceOrderRequestItemCartInner.


        :param item_id: The item_id of this PlaceOrderRequestItemCartInner.
        :type item_id: str
        """
        if item_id is None:
            raise ValueError("Invalid value for `item_id`, must not be `None`")  # noqa: E501
        if item_id is not None and len(item_id) > 40:
            raise ValueError("Invalid value for `item_id`, length must be less than or equal to `40`")  # noqa: E501
        if item_id is not None and len(item_id) < 40:
            raise ValueError("Invalid value for `item_id`, length must be greater than or equal to `40`")  # noqa: E501

        self._item_id = item_id

    @property
    def quantity(self) -> float:
        """Gets the quantity of this PlaceOrderRequestItemCartInner.

        Quantity of the specific item.  # noqa: E501

        :return: The quantity of this PlaceOrderRequestItemCartInner.
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: float):
        """Sets the quantity of this PlaceOrderRequestItemCartInner.

        Quantity of the specific item.  # noqa: E501

        :param quantity: The quantity of this PlaceOrderRequestItemCartInner.
        :type quantity: float
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity
