from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Profile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, name=None, phone=None, email=None, gender=None, dob=None):  # noqa: E501
        """Profile - a model defined in OpenAPI

        :param username: The username of this Profile.  # noqa: E501
        :type username: str
        :param name: The name of this Profile.  # noqa: E501
        :type name: str
        :param phone: The phone of this Profile.  # noqa: E501
        :type phone: float
        :param email: The email of this Profile.  # noqa: E501
        :type email: str
        :param gender: The gender of this Profile.  # noqa: E501
        :type gender: str
        :param dob: The dob of this Profile.  # noqa: E501
        :type dob: str
        """
        self.openapi_types = {
            'username': str,
            'name': str,
            'phone': float,
            'email': str,
            'gender': str,
            'dob': str
        }

        self.attribute_map = {
            'username': 'username',
            'name': 'name',
            'phone': 'phone',
            'email': 'email',
            'gender': 'gender',
            'dob': 'dob'
        }

        self._username = username
        self._name = name
        self._phone = phone
        self._email = email
        self._gender = gender
        self._dob = dob

    @classmethod
    def from_dict(cls, dikt) -> 'Profile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The profile of this Profile.  # noqa: E501
        :rtype: Profile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this Profile.


        :return: The username of this Profile.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Profile.


        :param username: The username of this Profile.
        :type username: str
        """

        self._username = username

    @property
    def name(self) -> str:
        """Gets the name of this Profile.


        :return: The name of this Profile.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Profile.


        :param name: The name of this Profile.
        :type name: str
        """

        self._name = name

    @property
    def phone(self) -> float:
        """Gets the phone of this Profile.


        :return: The phone of this Profile.
        :rtype: float
        """
        return self._phone

    @phone.setter
    def phone(self, phone: float):
        """Sets the phone of this Profile.


        :param phone: The phone of this Profile.
        :type phone: float
        """

        self._phone = phone

    @property
    def email(self) -> str:
        """Gets the email of this Profile.


        :return: The email of this Profile.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Profile.


        :param email: The email of this Profile.
        :type email: str
        """

        self._email = email

    @property
    def gender(self) -> str:
        """Gets the gender of this Profile.


        :return: The gender of this Profile.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """Sets the gender of this Profile.


        :param gender: The gender of this Profile.
        :type gender: str
        """
        allowed_values = ["Male", "Female", "Others"]  # noqa: E501
        if gender not in allowed_values:
            raise ValueError(
                "Invalid value for `gender` ({0}), must be one of {1}"
                .format(gender, allowed_values)
            )

        self._gender = gender

    @property
    def dob(self) -> str:
        """Gets the dob of this Profile.


        :return: The dob of this Profile.
        :rtype: str
        """
        return self._dob

    @dob.setter
    def dob(self, dob: str):
        """Sets the dob of this Profile.


        :param dob: The dob of this Profile.
        :type dob: str
        """

        self._dob = dob
