from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class VendorProductEditPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, item_id=None, name=None, thumbnail=None, price=None, max_quantity=None):  # noqa: E501
        """VendorProductEditPostRequest - a model defined in OpenAPI

        :param item_id: The item_id of this VendorProductEditPostRequest.  # noqa: E501
        :type item_id: str
        :param name: The name of this VendorProductEditPostRequest.  # noqa: E501
        :type name: str
        :param thumbnail: The thumbnail of this VendorProductEditPostRequest.  # noqa: E501
        :type thumbnail: str
        :param price: The price of this VendorProductEditPostRequest.  # noqa: E501
        :type price: float
        :param max_quantity: The max_quantity of this VendorProductEditPostRequest.  # noqa: E501
        :type max_quantity: float
        """
        self.openapi_types = {
            'item_id': str,
            'name': str,
            'thumbnail': str,
            'price': float,
            'max_quantity': float
        }

        self.attribute_map = {
            'item_id': 'itemId',
            'name': 'name',
            'thumbnail': 'thumbnail',
            'price': 'price',
            'max_quantity': 'maxQuantity'
        }

        self._item_id = item_id
        self._name = name
        self._thumbnail = thumbnail
        self._price = price
        self._max_quantity = max_quantity

    @classmethod
    def from_dict(cls, dikt) -> 'VendorProductEditPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _vendor_product_edit_post_request of this VendorProductEditPostRequest.  # noqa: E501
        :rtype: VendorProductEditPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item_id(self) -> str:
        """Gets the item_id of this VendorProductEditPostRequest.


        :return: The item_id of this VendorProductEditPostRequest.
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id: str):
        """Sets the item_id of this VendorProductEditPostRequest.


        :param item_id: The item_id of this VendorProductEditPostRequest.
        :type item_id: str
        """
        if item_id is None:
            raise ValueError("Invalid value for `item_id`, must not be `None`")  # noqa: E501
        if item_id is not None and len(item_id) > 40:
            raise ValueError("Invalid value for `item_id`, length must be less than or equal to `40`")  # noqa: E501
        if item_id is not None and len(item_id) < 40:
            raise ValueError("Invalid value for `item_id`, length must be greater than or equal to `40`")  # noqa: E501

        self._item_id = item_id

    @property
    def name(self) -> str:
        """Gets the name of this VendorProductEditPostRequest.


        :return: The name of this VendorProductEditPostRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VendorProductEditPostRequest.


        :param name: The name of this VendorProductEditPostRequest.
        :type name: str
        """

        self._name = name

    @property
    def thumbnail(self) -> str:
        """Gets the thumbnail of this VendorProductEditPostRequest.


        :return: The thumbnail of this VendorProductEditPostRequest.
        :rtype: str
        """
        return self._thumbnail

    @thumbnail.setter
    def thumbnail(self, thumbnail: str):
        """Sets the thumbnail of this VendorProductEditPostRequest.


        :param thumbnail: The thumbnail of this VendorProductEditPostRequest.
        :type thumbnail: str
        """

        self._thumbnail = thumbnail

    @property
    def price(self) -> float:
        """Gets the price of this VendorProductEditPostRequest.


        :return: The price of this VendorProductEditPostRequest.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this VendorProductEditPostRequest.


        :param price: The price of this VendorProductEditPostRequest.
        :type price: float
        """

        self._price = price

    @property
    def max_quantity(self) -> float:
        """Gets the max_quantity of this VendorProductEditPostRequest.


        :return: The max_quantity of this VendorProductEditPostRequest.
        :rtype: float
        """
        return self._max_quantity

    @max_quantity.setter
    def max_quantity(self, max_quantity: float):
        """Sets the max_quantity of this VendorProductEditPostRequest.


        :param max_quantity: The max_quantity of this VendorProductEditPostRequest.
        :type max_quantity: float
        """

        self._max_quantity = max_quantity
